language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

script:
  - python -m pip install .
  - cd test
  - python generate_testcase_data.py basic testcases/basic.rdl

after_success:
  - coveralls

stages:
  - test
  # Only execute deployment stage on tagged release commits in the form of "v1.2.3"
  # and from your repository (e.g. not PRs).
  # Also allows alpha/beta releases such as "v1.2.3b2"
  - name: deploy
    if: repo = SystemRDL/PeakRDL-uvm AND tag =~ ^v\d+\.\d+\.\w+$

jobs:
  include:
    # Run lint
    - name: Lint
      install:
        - python -m pip install pylint
        - python -m pip install .
      script: pylint --rcfile test/pylint.rc peakrdl

    # Deploy source distribution
    - stage: deploy
      name: Deploy source distribution
      install: python -m pip install twine
      script: python setup.py sdist --formats=gztar
      after_success: python -m twine upload --skip-existing dist/*.tar.gz
